site_name: lekhraj-Dinkar-Docs
site_description: Technical Documentation
site_author: lekhraj Dinkar

# Navigation based on your Notes folder
nav:
  - Home: README.md
  - Frontend:
      - Overview: 00_Frontend/readme.md
  - Springboot:
      - Others: 00_Springboot/00_others.md
      - Spring Core:
          - Spring Core Basics: 00_Springboot/01_Spring-core/01_Spring_Core.md
          - Spring Bean Lifecycle: 00_Springboot/01_Spring-core/02_Spring_bean_lifeCycle.md
          - AOP Concept: 00_Springboot/01_Spring-core/03_AOP_concept.md
          - Point-cut Examples: 00_Springboot/01_Spring-core/03_point-cut-examples.txt
          - Spring Properties: 00_Springboot/01_Spring-core/04_spring_properties.md
      - Spring Boot:
          - Kickoff: 00_Springboot/01_springboot/01_SB_kickoff.md
          - Auto Configuration: 00_Springboot/01_springboot/02_SB_AutoConfig.md
          - Starter & Testing: 00_Springboot/01_springboot/03_SB_starter_test.md
      - Web:
          - Web Start: 00_Springboot/02_web/00 WEB_start.md
          - General Web Tasks: 00_Springboot/02_web/00_general_web_task.md
          - Servlet 3: 00_Springboot/02_web/01_servlet_3.md
          - Spring MVC: 00_Springboot/02_web/02_spring_MVC.md
          - Spring Boot Starter Web: 00_Springboot/02_web/03_spring_boot_stater_web.md
          - REST: 00_Springboot/02_web/04_REST.md
          - Jackson: 00_Springboot/02_web/05_Jackson.md
          - Swagger: 00_Springboot/02_web/06_swagger.md
          - Error Handling: 00_Springboot/02_web/07_error_handling.md
          - gRPC & Webflux: 00_Springboot/02_web/08_gRPC+webflux.md
          - Webflux: 00_Springboot/02_web/09_webflux.md
      - Data Layer:
          - Common Tasks: 00_Springboot/03_data-layer/00_common_task.md
          - JPA: 00_Springboot/03_data-layer/01_JPA.md
          - Persistence Context: 00_Springboot/03_data-layer/02_presistence-context.md
          - ACID & Locks: 00_Springboot/03_data-layer/03_ACID+Locks.md
          - Hibernate Annotations & Converter: 00_Springboot/03_data-layer/04_Hibernate-1-anno+converter.md
          - Hibernate Identifier & Validator: 00_Springboot/03_data-layer/04_Hibernate-2-identifier+validator.md
          - Hibernate Query: 00_Springboot/03_data-layer/04_Hibernate-3-query.md
          - SB JPA Data Part 1: 00_Springboot/03_data-layer/05-SBjpaData-1-start.md
          - SB JPA Data Part 2: 00_Springboot/03_data-layer/05-SBjpaData-2.md
          - SB JPA Data Transactions: 00_Springboot/03_data-layer/05-SBjpaData-3-txn.md
          - ER Diagram: 00_Springboot/03_data-layer/er-diagram.png
      - Security:
          - OAuth 2.0: 00_Springboot/04_security/00_OAuth_2.0.md
          - Spring Boot Security Start: 00_Springboot/04_security/01_sb-security-start.md
          - Authentication: 00_Springboot/04_security/02_Authentication.md
          - Authorization: 00_Springboot/04_security/03_Authorization.md
          - REST Security: 00_Springboot/04_security/04_REST-secure.md

theme:
  name: material
  features:
    - navigation.side
    - navigation.sections
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: indigo
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: indigo
      accent: indigo

repo_url: https://github.com/lekhrajdinkar/02-backend-java-spring
repo_name: GitHub
edit_uri: edit/main/Notes/

markdown_extensions:
  - admonition
  - toc:
      permalink: true
  - pymdownx.superfences
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.betterem
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde

plugins:
  - search
