namespace: "dev1-helm"

replicaCount: 1
containerPort: 8083
springProfile: dev1

image:
  repository: lekhrajdinkar18/02-backend-java-spring
  pullPolicy: IfNotPresent
  tag: "spring-app-06.04.2025"

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  automount: true # Automatically mount a ServiceAccount's API credentials?
  annotations: {}
  name: "sa-1"

podAnnotations: {}
podLabels: {}
podSecurityContext: {}
securityContext: {}

service:
  type: NodePort
  port: 80

ingress:
  enabled: false
  className: ""
  annotations: {}
  hosts:
    - host: chart-example.local
      paths:
        - path: /
          pathType: Prefix
  tls: []

resources: {}

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

# Additional volumes on the output Deployment definition.
volumes: []
volumeMounts: []
nodeSelector: {}
tolerations: []
affinity: {}


