AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: A simple AWS SAM example

Resources:
  HelloWorldFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: app.lambda_handler
      Runtime: python3.11
      CodeUri: lambda/
      Environment:
        Variables:
          # TABLE_NAME: HelloWorldTable
          TABLE_NAME: !Ref HelloWorldTable
          REGION_NAME: !Ref AWS::Region

      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref HelloWorldTable

      Events:
        HelloWorldApi:
          Type: Api
          Properties:
            Path: /hello
            Method: get

  HelloWorldTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: HelloWorldTable
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5