apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-app-deployment
  namespace: dev-ns
  labels:
    app: spring-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spring-app
  template:
    metadata:
      labels:
        app: spring-app
    spec:
      serviceAccountName: spring-app-sa
      containers:
        - name: spring-app
          image: lekhrajdinkar18/spring-app:latest
          ports:
            - containerPort: 8083  # Adjust this port based on the app's configuration

---
apiVersion: v1
kind: Service
metadata:
  name: spring-app-service
  namespace: dev-ns
spec:
  type: LoadBalancer
  selector:
    app: spring-app
  ports:
    - protocol: TCP
      port: 8080         # The service port
      targetPort: 8083   # The container's port
