# Please edit the object below. Lines beginning with a '#' will be ignored,
# and an empty file will abort the edit. If an error occurs while saving this file will be
# reopened with the relevant failures.
#
apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      - system:node-proxier
      rolearn: arn:aws:iam::533267082359:role/maps-outbound-us-west-2-dev2-pod-exec-role
      username: system:node:{{SessionName}}

    - rolearn: arn:aws:iam::533267082359:role/eks-cluster-role-1-for-federated-user
      username: arn:aws:iam::533267082359:role/eks-cluster-role-1-for-federated-user
      groups:
      - system:masters

  mapUsers: |
    - userarn: arn:aws:iam::533267082359:user/lekhrajdinkar-eks-user
      username: arn:aws:iam::533267082359:user/lekhrajdinkar-eks-user
      groups:
        - system:masters

kind: ConfigMap

metadata:
  creationTimestamp: "2024-11-17T23:07:57Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "28125"
  uid: 15c891c8-dbd1-49b0-a04b-4053e4a7cac1
