apiVersion: v1
kind: Service
metadata:
  name: {{ include "spring-helm.fullname" . }}
  labels:
    {{- include "spring-helm.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - targetPort: {{ .Values.containerPort }}
      port: {{ .Values.service.port }}
      nodePort: 30008
  selector:
    {{- include "spring-helm.selectorLabels" . | nindent 4 }}
